arch:
 - amd64
 - ppc64le
language: node_js

node_js:
  - 12 # LTS
  - 14 # Current

env:
  - CHAI_VERSION=^4.0.0 SINON_VERSION=^10.0.0
  - CHAI_VERSION=^4.0.0 SINON_VERSION=^9.0.0
  - CHAI_VERSION=^4.0.0 SINON_VERSION=^8.0.0
  - CHAI_VERSION=^4.0.0 SINON_VERSION=^7.0.0
  - CHAI_VERSION=^4.0.0 SINON_VERSION=^6.0.0
  - CHAI_VERSION=^4.0.0 SINON_VERSION=^5.0.0
  - CHAI_VERSION=^4.0.0 SINON_VERSION=^4.0.0

script:
  - npm run lint
  - npm run test-travis
